#include <algorithm>
#include <any>
#include <array>
#include <chrono>
#include <climits>
#include <concepts>
#include <csetjmp>
#include <csignal>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <exception>
#include <filesystem>
#include <format>
#include <fstream>
#include <functional>
#include <iomanip>
#include <ios>
#include <iosfwd>
#include <iostream>
#include <iterator>
#include <list>
#include <map>
#include <memory>
#include <mutex>
#include <optional>
#include <ostream>
#include <random>
#include <ranges>
#include <regex>
#include <set>
#include <sstream>
#include <streambuf>
#include <string>
#include <thread>
#include <tuple>
#include <unistd.h>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

#include "Compositor.hpp"
#include "SharedDefs.hpp"
#include "Window.hpp"
#include "config/ConfigDataValues.hpp"
#include "config/ConfigManager.hpp"
#include "config/defaultConfig.hpp"
#include "debug/CrashReporter.hpp"
#include "debug/HyprCtl.hpp"
#include "debug/HyprDebugOverlay.hpp"
#include "debug/HyprNotificationOverlay.hpp"
#include "debug/Log.hpp"
#include "debug/TracyDefines.hpp"
#include "events/Events.hpp"
#include "helpers/AnimatedVariable.hpp"
#include "helpers/BezierCurve.hpp"
#include "helpers/Color.hpp"
#include "helpers/MiscFunctions.hpp"
#include "helpers/Monitor.hpp"
#include "helpers/Region.hpp"
#include "helpers/Splashes.hpp"
#include "helpers/SubsurfaceTree.hpp"
#include "helpers/Timer.hpp"
#include "helpers/VarList.hpp"
#include "helpers/Vector2D.hpp"
#include "helpers/WLClasses.hpp"
#include "helpers/WLListener.hpp"
#include "helpers/WLSurface.hpp"
#include "helpers/Workspace.hpp"
#include "hyprerror/HyprError.hpp"
#include "includes.hpp"
#include "init/initHelpers.hpp"
#include "layout/DwindleLayout.hpp"
#include "layout/IHyprLayout.hpp"
#include "layout/MasterLayout.hpp"
#include "macros.hpp"
#include "managers/AnimationManager.hpp"
#include "managers/EventManager.hpp"
#include "managers/HookSystemManager.hpp"
#include "managers/KeybindManager.hpp"
#include "managers/LayoutManager.hpp"
#include "managers/ProtocolManager.hpp"
#include "managers/SessionLockManager.hpp"
#include "managers/ThreadManager.hpp"
#include "managers/XWaylandManager.hpp"
#include "managers/input/InputManager.hpp"
#include "managers/input/InputMethodRelay.hpp"
#include "plugins/HookSystem.hpp"
#include "plugins/PluginAPI.hpp"
#include "plugins/PluginSystem.hpp"
#include "protocols/FractionalScale.hpp"
#include "protocols/GlobalShortcuts.hpp"
#include "protocols/Screencopy.hpp"
#include "protocols/TextInputV1.hpp"
#include "protocols/WaylandProtocol.hpp"
#include "protocols/XDGOutput.hpp"
#include "render/Framebuffer.hpp"
#include "render/OpenGL.hpp"
#include "render/Renderer.hpp"
#include "render/Shader.hpp"
#include "render/Shaders.hpp"
#include "render/Texture.hpp"
#include "render/decorations/CHyprDropShadowDecoration.hpp"
#include "render/decorations/CHyprGroupBarDecoration.hpp"
#include "render/decorations/IHyprWindowDecoration.hpp"
#include "render/shaders/Border.hpp"
#include "render/shaders/Shadow.hpp"
#include "render/shaders/Textures.hpp"

