body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > Please do **not** use AI to make feature requests. Fill this request with your own words. We don't care about your poor grammar.
        > It's much more clear to us if you don't use AI and instead write a clear, concise request yourself.
  - type: textarea
    attributes:
      label: What's the problem?
      description: |
        What problem are you trying to solve?
      placeholder: |
        I wanted to do...
    validations:
      required: true
  - type: textarea
    attributes:
      label: What's your proposed solution?
      description: |
        How would you want it solved?
      placeholder: |
        We could add ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Attachments
      description: |
        Please attach any logs or images that can help clarify the feature.
        You can attach by dragging and dropping files into the textbox below.
      placeholder: |
        attachments...
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: "I acknowledge that:"
      options:
        - label: |
            I have searched **all** (open and closed) discussions and issues, checked the wiki, and my feature is not there.
          required: true
        - label: |
            I have read the [Code of Conduct](https://github.com/hyprwm/.github/blob/main/policies/CODE_OF_CONDUCT.md) and agree to follow it.
          required: true
        - label: |
            I wrote this request with my own hands, my own keyboard, and in my own words.
          required: true
