name: Build Hyprland (Nix)

on: [push, pull_request, workflow_dispatch]
jobs:
  nix:
    name: "Build Hyprland (Nix)"
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install nix
      uses: cachix/install-nix-action@v17
      with:
        install_url: https://releases.nixos.org/nix/nix-2.8.0/install
        extra_nix_config: |
          auto-optimise-store = true
          experimental-features = nix-command flakes
    - name: Build HyprLand with default settings
      run: nix build --print-build-logs
