name: Feature Request
description: I'd like to request additional functionality
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Before opening a new issue, take a moment to search through the current open ones.

        ---

  - type: textarea
    id: desc
    attributes:
      label: Description
      description: "Describe your idea"
    validations:
      required: true

