#pragma once

#include <array>
#include <string>

inline const std::vector<std::string> SPLASHES = {
    "Woo, animations!",
    "It's like Hypr, but better.",
    "Release 1.0 when?",
    "It's not awesome, it's Hyprland!",
    "\"I commit too often, people can't catch up lmao\" - Vaxry",
    "This text is random.",
    "\"There are reasons to not use rust.\" - Boga",
    "Read the wiki.",
    "\"Hello everyone this is YOUR daily dose of ‘read the wiki’\" - Vaxry",
    "h",
    "\"‘why no work’, bro I haven't hacked your pc to get live feeds yet\" - Vaxry",
    "Compile, wait for 20 minutes, notice a new commit, compile again.",
    "To rice, or not to rice, that is the question.",
    "Now available on Fedora!",
    // music reference / quote section
    "J'remue le ciel, le jour, la nuit.",
    "aezakmi, aezakmi, aezakmi, aezakmi, aezakmi, aezakmi, aezakmi!",
    "Wir sind schon sehr lang zusammen...",
    "I see a red door and I want it painted black.",
    "Take on me, take me on...",
    "You spin me right round baby right round",
    "Stayin' alive, stayin' alive",
    "Say no way, say no way ya, no way!",
    "Ground control to Major Tom...",
    "Alors on danse",
    "And all that I can see, is just a yellow lemon tree.",
    "Got a one-way ticket to the blues",
    "Is this the real life, is this just fantasy",
    "What's in your head, in your head?",
    "We're all living in America, America, America.",
    "I'm still standing, better than I ever did",
    "Here comes the sun, bringing you love and shining on everyone",
    "Two trailer park girls go round the outside",
    "With the lights out, it's less dangerous",
    "Here we go back, this is the moment, tonight is the night",
    "Now you're just somebody that I used to know...",
    "Black bird, black moon, black sky",
    "Some legends are told, some turn to dust or to gold",
    "Your brain gets smart, but your head gets dumb.",
    "Save your mercy for someone who needs it more",
    "You're gonna hear my voice when I shout it out loud",
    "Ding ding pch n daa, bam-ba-ba-re-bam baram bom bom baba-bam-bam-bommm",
    "Súbeme la radio que esta es mi canción",
    "I'm beggin', beggin' you",
    "Never gonna let you down (I am trying!)",
    "\"I use Arch, btw\" - John Cena",
    "\"Hyper\".replace(\"e\", \"\")",
    "\"my win11 install runs hyprland that is true\" - raf",
    "\"stop playing league loser\" - hyprBot",
    "\"If it ain't broke, don't fix it\" - Lucascito_03",
    "\"@vaxry how do i learn c++\" - flicko",
    //
    "Join the discord server!",
    "Thanks ThatOneCalculator!",
    "The AUR packages always work, except for the times they don't.",
    "Funny animation compositor woo"
};