#include "../../hyprctlCompat.hpp"
#include "../../shared.hpp"
#include "tests.hpp"

#include <chrono>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <string_view>
#include <thread>
#include <hyprutils/utils/ScopeGuard.hpp>

using namespace Hyprutils::Utils;

// Generated by hyprtester/fixtures/cursor-none.py; no generator/dependency is
// needed at runtime. Native 24px red and 32px green, resize_algorithm = none.
static constexpr std::string_view CURSOR_ARCHIVE = "504b030414000000000000002100978dd4bf8500000085000000070000006d6574612e686c686f7473706f745f78203d20302e32350a686f7473706f"
                                                   "745f79203d20302e350a726573697a655f616c676f726974686d203d206e6f6e650a646566696e655f73697a65203d2032342c2032342e706e670a64"
                                                   "6566696e655f73697a65203d2033322c2033322e706e670a646566696e655f6f76657272696465203d2064656661756c740a504b0304140000000000"
                                                   "000021002dc6a3f55e0000005e0000000600000032342e706e6789504e470d0a1a0a0000000d4948445200000018000000180806000000e0773df800"
                                                   "00002549444154789c63f8cfc0f09f969861d482510b462d18b560d482510b462d18b56068580000c4d67bbdbd6c4f8b0000000049454e44ae426082"
                                                   "504b030414000000000000002100e7cd76a163000000630000000600000033322e706e6789504e470d0a1a0a0000000d494844520000002000000020"
                                                   "0806000000737a7af40000002a49444154789cedce310d0000000220fb97d6183e8c02243d13101010101010101010101010101078070657d1f86a2d"
                                                   "1b0f980000000049454e44ae426082504b0102140314000000000000002100978dd4bf85000000850000000700000000000000000000008001000000"
                                                   "006d6574612e686c504b01021403140000000000000021002dc6a3f55e0000005e0000000600000000000000000000008001aa00000032342e706e67"
                                                   "504b0102140314000000000000002100e7cd76a1630000006300000006000000000000000000000080012c01000033322e706e67504b050600000000"
                                                   "030003009d000000b30100000000";

static constexpr const char*      CURSOR_LEFT  = "HYPRTEST-CURSOR-LEFT";
static constexpr const char*      CURSOR_RIGHT = "HYPRTEST-CURSOR-RIGHT";

static std::string                cursorMonitorBlock(const std::string& name) {
    const auto MONITORS = getFromSocket("/monitors all");
    const auto BEGIN    = MONITORS.find(std::format("Monitor {} (ID ", name));
    if (BEGIN == std::string::npos)
        return "";

    const auto END = MONITORS.find("\n\n", BEGIN);
    return MONITORS.substr(BEGIN, END == std::string::npos ? std::string::npos : END - BEGIN);
}

static bool waitForCursorOutput(const std::string& name, double scale, int transform, int x) {
    for (int i = 0; i < 50; ++i) {
        const auto BLOCK = cursorMonitorBlock(name);
        if (BLOCK.contains(std::format("scale: {}\n", scale)) && BLOCK.contains(std::format("transform: {}\n", transform)) && BLOCK.contains(std::format(" at {}x0\n", x)) &&
            BLOCK.contains("disabled: false"))
            return true;
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }
    NLog::log("Cursor output did not settle: {}", cursorMonitorBlock(name));
    return false;
}

static bool waitForCursorOutputRemoved(const std::string& name) {
    for (int i = 0; i < 50; ++i) {
        if (cursorMonitorBlock(name).empty())
            return true;
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }
    return false;
}

static std::string expectCursorRender(const std::string& name, int pixels) {
    const auto ARMED = getFromSocket(std::format("/eval hl.plugin.test.arm_cursor_render('{}', {})", name, pixels));
    if (ARMED != "ok")
        return ARMED;

    for (int i = 0; i < 50; ++i) {
        const auto RESULT = getFromSocket("/eval hl.plugin.test.check_cursor_render()");
        if (!RESULT.contains("Cursor render pending"))
            return RESULT;
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }
    return std::format("Timed out waiting for cursor render on {}", name);
}

TEST_CASE(cursorPerOutputHyprcursor) {
    const auto HOME = std::getenv("HOME");
    ASSERT(HOME != nullptr, true);
    const auto      NAME  = std::format("hyprtester-cursor-none-{}", std::chrono::steady_clock::now().time_since_epoch().count());
    const auto      ROOT  = std::filesystem::path{HOME} / ".icons";
    const auto      THEME = ROOT / NAME;
    std::error_code ec;
    std::filesystem::create_directories(ROOT, ec);
    ASSERT(ec.value(), 0);
    ASSERT(std::filesystem::create_directory(THEME, ec), true);
    CScopeGuard removeFixture([&] { std::filesystem::remove_all(THEME, ec); });
    ASSERT(std::filesystem::create_directory(THEME / "cursors", ec), true);
    {
        std::ofstream manifest(THEME / "manifest.hl");
        manifest << "name = " << NAME << "\nversion = 1\ncursors_directory = cursors\n";
        manifest.close();
        ASSERT(manifest.fail(), false);
        std::ofstream              archive(THEME / "cursors/left_ptr.hc", std::ios::binary);
        constexpr std::string_view HEX = "0123456789abcdef";
        for (size_t i = 0; i < CURSOR_ARCHIVE.size(); i += 2)
            archive.put(static_cast<char>((HEX.find(CURSOR_ARCHIVE[i]) << 4) | HEX.find(CURSOR_ARCHIVE[i + 1])));
        archive.close();
        ASSERT(archive.fail(), false);
    }

    // Only remove outputs created by this invocation, including on assertions.
    ASSERT(cursorMonitorBlock(CURSOR_LEFT).empty(), true);
    ASSERT(cursorMonitorBlock(CURSOR_RIGHT).empty(), true);
    bool        leftCreated = false, rightCreated = false;
    CScopeGuard cleanup([&] {
        if (rightCreated) {
            EXPECT_OK(getFromSocket(std::format("/output remove {}", CURSOR_RIGHT)));
            EXPECT(waitForCursorOutputRemoved(CURSOR_RIGHT), true);
        }
        if (leftCreated) {
            EXPECT_OK(getFromSocket(std::format("/output remove {}", CURSOR_LEFT)));
            EXPECT(waitForCursorOutputRemoved(CURSOR_LEFT), true);
        }
        // Reload restores config/monitor rules; the saved theme is restored
        // afterwards because it need not have come from the config file.
        EXPECT_OK(getFromSocket("/reload"));
        EXPECT_OK(getFromSocket("/eval hl.plugin.test.restore_cursor_fixture()"));
    });

    OK(getFromSocket("/eval hl.config({ cursor = { enable_hyprcursor = true, no_hardware_cursors = 1 } })"));
    OK(getFromSocket(std::format("/eval hl.monitor({{ output = '{}', mode = '800x600@60', position = '5000x0', scale = '1' }}); "
                                 "hl.monitor({{ output = '{}', mode = '1000x750@60', position = '5800x0', scale = '1.25' }})",
                                 CURSOR_LEFT, CURSOR_RIGHT)));
    auto result = getFromSocket(std::format("/output create headless {}", CURSOR_LEFT));
    leftCreated = result == "ok";
    OK(result);
    result       = getFromSocket(std::format("/output create headless {}", CURSOR_RIGHT));
    rightCreated = result == "ok";
    OK(result);
    ASSERT(waitForCursorOutput(CURSOR_LEFT, 1, 0, 5000), true);
    ASSERT(waitForCursorOutput(CURSOR_RIGHT, 1.25, 0, 5800), true);
    OK(getFromSocket(std::format("/eval hl.plugin.test.start_cursor_fixture('{}')", NAME)));
    ASSERT(getFromSocket("/cursorpos"), "5798, 100");
    EXPECT_OK(expectCursorRender(CURSOR_LEFT, 24));
    EXPECT_OK(expectCursorRender(CURSOR_RIGHT, 32));

    // Rotate the 1x output and keep its right edge, and the pointer, stationary.
    OK(getFromSocket(std::format("/eval hl.monitor({{ output = '{}', mode = '800x600@60', position = '5200x0', scale = '1', transform = 3 }})", CURSOR_LEFT)));
    ASSERT(waitForCursorOutput(CURSOR_LEFT, 1, 3, 5200), true);
    EXPECT(getFromSocket("/cursorpos"), "5798, 100");
    EXPECT_OK(expectCursorRender(CURSOR_LEFT, 24));
    EXPECT_OK(expectCursorRender(CURSOR_RIGHT, 32));

    // No setCursorFromName or pointer move may refresh the image between these
    // changes: monitor layout notifications must update the installed buffers.
    for (const double SCALE : {1.0, 1.25}) {
        OK(getFromSocket(std::format("/eval hl.monitor({{ output = '{}', mode = '1000x750@60', position = '5800x0', scale = '{}' }})", CURSOR_RIGHT, SCALE)));
        ASSERT(waitForCursorOutput(CURSOR_RIGHT, SCALE, 0, 5800), true);
        EXPECT(getFromSocket("/cursorpos"), "5798, 100");
        EXPECT_OK(expectCursorRender(CURSOR_LEFT, 24));
        EXPECT_OK(expectCursorRender(CURSOR_RIGHT, SCALE == 1.0 ? 24 : 32));
    }

    // Explicit reset and a null client cursor surface must clear every scale,
    // including cached textures. Reinstalling the named image must recover both.
    for (const auto ACTION : {"reset", "surface"}) {
        OK(getFromSocket(std::format("/eval hl.plugin.test.cursor_fixture_image('{}')", ACTION)));
        EXPECT_OK(expectCursorRender(CURSOR_LEFT, 0));
        EXPECT_OK(expectCursorRender(CURSOR_RIGHT, 0));
        // Neither a pending animation tick nor a theme/layout refresh may resurrect the hidden image.
        OK(getFromSocket("/eval hl.plugin.test.cursor_fixture_image('refresh')"));
        EXPECT_OK(expectCursorRender(CURSOR_LEFT, 0));
        EXPECT_OK(expectCursorRender(CURSOR_RIGHT, 0));
        OK(getFromSocket("/eval hl.plugin.test.cursor_fixture_image('default')"));
        EXPECT_OK(expectCursorRender(CURSOR_LEFT, 24));
        EXPECT_OK(expectCursorRender(CURSOR_RIGHT, 32));
    }

    OK(getFromSocket(std::format("/output remove {}", CURSOR_RIGHT)));
    rightCreated = false;
    ASSERT(waitForCursorOutputRemoved(CURSOR_RIGHT), true);
    // Output removal may focus another monitor and warp the pointer. Move back
    // onto the survivor without explicitly reinstalling the named cursor.
    OK(getFromSocket("/dispatch hl.dsp.cursor.move({ x = 5500, y = 100 })"));
    EXPECT_OK(expectCursorRender(CURSOR_LEFT, 24));
}
