#include "tests.hpp"
#include "../../shared.hpp"
#include "../../hyprctlCompat.hpp"
#include <print>
#include <thread>
#include <chrono>
#include <hyprutils/os/Process.hpp>
#include <hyprutils/memory/WeakPtr.hpp>
#include <csignal>
#include <cerrno>
#include "../shared.hpp"

using namespace Hyprutils::OS;
using namespace Hyprutils::Memory;

#define UP CUniquePointer
#define SP CSharedPointer

TEST_CASE(persistentWorkspaces) {
    // test on workspace "window"
    NLog::log("{}Switching to workspace 1", Colors::YELLOW);
    getFromSocket("/dispatch hl.dsp.focus({ workspace = '1' })"); // no OK: we might be on 1 already

    OK(getFromSocket("/eval hl.workspace_rule({ workspace = '5', monitor = 'HEADLESS-2', persistent = true })"));
    OK(getFromSocket("/eval hl.workspace_rule({ workspace = '6', monitor = 'HEADLESS-PERSISTENT-TEST', persistent = true })"));
    OK(getFromSocket("/eval hl.workspace_rule({ workspace = 'name:PERSIST', monitor = 'HEADLESS-PERSISTENT-TEST', persistent = true })"));
    OK(getFromSocket("/eval hl.workspace_rule({ workspace = 'name:PERSIST-2', monitor = 'HEADLESS-PERSISTENT-TEST', persistent = true })"));

    {
        auto str = getFromSocket("/workspaces");
        ASSERT_CONTAINS(str, "ID 5 (5)");
        ASSERT_COUNT_STRING(str, "workspace ID ", 2);
    }

    OK(getFromSocket("/output create headless HEADLESS-PERSISTENT-TEST"));

    {
        auto str = getFromSocket("/monitors");
        ASSERT_CONTAINS(str, "HEADLESS-PERSISTENT-TEST");
    }

    OK(getFromSocket("/dispatch hl.dsp.focus({ monitor = 'HEADLESS-PERSISTENT-TEST' })"));

    {
        auto str = getFromSocket("/workspaces");
        ASSERT_CONTAINS(str, "ID 2 (2)"); // this should be automatically generated by hl
        ASSERT_CONTAINS(str, "ID 5 (5)");
        ASSERT_CONTAINS(str, "ID 6 (6)");
        ASSERT_CONTAINS(str, "(PERSIST) on monitor");
        ASSERT_CONTAINS(str, "(PERSIST-2) on monitor");
        ASSERT_COUNT_STRING(str, "workspace ID ", 6);
    }

    OK(getFromSocket("/reload"));

    {
        auto str = getFromSocket("/workspaces");
        ASSERT_NOT_CONTAINS(str, "ID 5 (5)");
        ASSERT_NOT_CONTAINS(str, "ID 6 (6)");
        ASSERT_NOT_CONTAINS(str, "(PERSIST) on monitor");
        ASSERT_COUNT_STRING(str, "workspace ID ", 2);
    }

    OK(getFromSocket("/output remove HEADLESS-PERSISTENT-TEST"));
}
