#include "tests.hpp"
#include "../../shared.hpp"
#include "../../hyprctlCompat.hpp"
#include <hyprutils/os/Process.hpp>
#include <hyprutils/memory/WeakPtr.hpp>
#include <hyprutils/utils/ScopeGuard.hpp>
#include <chrono>
#include <format>
#include <thread>

using namespace Hyprutils::OS;
using namespace Hyprutils::Memory;
using namespace Hyprutils::Utils;

#define UP CUniquePointer
#define SP CSharedPointer

static bool waitForMonitor(const std::string& name, bool present, bool all = true) {
    for (int i = 0; i < 50; ++i) {
        if (getFromSocket(all ? "/monitors all" : "/monitors").contains(name) == present)
            return true;

        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }

    return false;
}

static bool waitForWorkspace(const std::string& workspace, bool present) {
    for (int i = 0; i < 50; ++i) {
        if (getFromSocket("/workspaces").contains(workspace) == present)
            return true;

        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }

    return false;
}

TEST_CASE(persistentWorkspaces) {
    // test on workspace "window"
    NLog::log("{}Switching to workspace 1", Colors::YELLOW);
    getFromSocket("/dispatch hl.dsp.focus({ workspace = '1' })"); // no OK: we might be on 1 already

    OK(getFromSocket("/eval hl.workspace_rule({ workspace = '5', monitor = 'HEADLESS-2', persistent = true })"));
    OK(getFromSocket("/eval hl.workspace_rule({ workspace = '6', monitor = 'HEADLESS-PERSISTENT-TEST', persistent = true })"));
    OK(getFromSocket("/eval hl.workspace_rule({ workspace = 'name:PERSIST', monitor = 'HEADLESS-PERSISTENT-TEST', persistent = true })"));
    OK(getFromSocket("/eval hl.workspace_rule({ workspace = 'name:PERSIST-2', monitor = 'HEADLESS-PERSISTENT-TEST', persistent = true })"));
    OK(getFromSocket("/eval hl.workspace_rule({ workspace = 'special:PERSIST-SPECIAL', persistent = true })"));

    Tests::sync();
    EXPECT_NOT_CONTAINS(getFromSocket("/workspaces"), "workspace special:PERSIST-SPECIAL (special:PERSIST-SPECIAL)");
    OK(getFromSocket("/dispatch hl.dsp.workspace.toggle_special('PERSIST-SPECIAL')"));
    ASSERT(getFromSocket("/repl hl.get_workspace('special:PERSIST-SPECIAL').is_persistent"), "false");
    OK(getFromSocket("/dispatch hl.dsp.workspace.toggle_special('PERSIST-SPECIAL')"));
    Tests::sync();
    EXPECT_NOT_CONTAINS(getFromSocket("/workspaces"), "workspace special:PERSIST-SPECIAL (special:PERSIST-SPECIAL)");

    {
        auto str = getFromSocket("/workspaces");
        EXPECT_CONTAINS(str, "workspace 5 (5)");
        EXPECT_COUNT_STRING(str, "workspace ", 2);
    }

    OK(getFromSocket("/output create headless HEADLESS-PERSISTENT-TEST"));
    Tests::sync();
    OK(getFromSocket("/eval hl.plugin.test.expect_workspace_lifecycle_state('HEADLESS-PERSISTENT-TEST')"));

    {
        auto str = getFromSocket("/monitors");
        ASSERT_CONTAINS(str, "HEADLESS-PERSISTENT-TEST");
    }

    OK(getFromSocket("/dispatch hl.dsp.focus({ monitor = 'HEADLESS-PERSISTENT-TEST' })"));

    {
        auto str = getFromSocket("/workspaces");
        EXPECT_CONTAINS(str, "workspace 2 (2)"); // this should be automatically generated by hl
        EXPECT_CONTAINS(str, "workspace 5 (5)");
        EXPECT_CONTAINS(str, "workspace 6 (6)");
        EXPECT_CONTAINS(str, "(PERSIST) on monitor");
        EXPECT_CONTAINS(str, "(PERSIST-2) on monitor");
        EXPECT_COUNT_STRING(str, "workspace ", 6);
    }

    OK(getFromSocket("/reload"));

    {
        auto str = getFromSocket("/workspaces");
        EXPECT_NOT_CONTAINS(str, "workspace 5 (5)");
        EXPECT_NOT_CONTAINS(str, "workspace 6 (6)");
        EXPECT_NOT_CONTAINS(str, "(PERSIST) on monitor");
        EXPECT_COUNT_STRING(str, "workspace ", 2);
    }

    OK(getFromSocket("/output remove HEADLESS-PERSISTENT-TEST"));
}

TEST_CASE(workspaceLifecycleReleasesEmptyWorkspaces) {
    static constexpr const char* MONITOR   = "HEADLESS-LIFECYCLE-OWNERSHIP";
    static constexpr const char* WORKSPACE = "410";

    CScopeGuard                  guard = {[&]() {
        if (getFromSocket("/monitors all").contains(MONITOR))
            getFromSocket(std::format("/output remove {}", MONITOR));
        getFromSocket("/reload");
    }};

    getFromSocket(std::format("/output remove {}", MONITOR));
    ASSERT(waitForMonitor(MONITOR, false), true);
    OK(getFromSocket(std::format("/eval hl.monitor({{ output = '{}', mode = '1920x1080@60', position = 'auto-right', scale = '1' }})", MONITOR)));
    OK(getFromSocket(std::format("/output create headless {}", MONITOR)));
    ASSERT(waitForMonitor(MONITOR, true, false), true);
    OK(getFromSocket(std::format("/dispatch hl.dsp.focus({{ monitor = '{}' }})", MONITOR)));
    OK(getFromSocket(std::format("/dispatch hl.dsp.focus({{ workspace = '{}' }})", WORKSPACE)));
    ASSERT_CONTAINS(getFromSocket("/activeworkspace"), "workspace 410 (410)");

    OK(getFromSocket(std::format("/output remove {}", MONITOR)));
    ASSERT(waitForMonitor(MONITOR, false), true);
    ASSERT(waitForWorkspace("workspace 410 (410)", false), true);

    OK(getFromSocket(std::format("/output create headless {}", MONITOR)));
    ASSERT(waitForMonitor(MONITOR, true, false), true);
    ASSERT(waitForWorkspace("workspace 410 (410)", false), true);

    OK(getFromSocket(std::format("/output remove {}", MONITOR)));
    ASSERT(waitForMonitor(MONITOR, false), true);
}
