name: Build man pages

on:
  workflow_dispatch:
  push:
    paths:
      - docs/**
    branches:
      - 'main'

jobs:
  main:
    name: Build man pages
    runs-on: ubuntu-latest
    steps:
    - name: Install deps
      run: sudo apt install pandoc
    - name: Clone repository
      uses: actions/checkout@v3
      # Not needed
      # with:
      #   submodules: recursive
    - name: Build man pages
      run: make man
    - uses: stefanzweifel/git-auto-commit-action@v4
      name: Commit
      with:
        commit_message: "[gha] build man pages"
        commit_user_name: Mihai Fufezan
        commit_user_email: fufexan@protonmail.com
        commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
