name: "Nix: update lockfile"

on: [push, workflow_dispatch]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Install nix
      uses: cachix/install-nix-action@v18
      with:
        install_url: https://nixos.org/nix/install
        extra_nix_config: |
          auto-optimise-store = true
          experimental-features = nix-command flakes
    - name: Update lockfile
      run: nix/update-inputs.sh
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[gha] bump flake inputs"
