name: Nix

on:
  workflow_call:
    secrets:
      PAT:
        required: true

jobs:
  update:
    name: wlroots
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}

    - uses: DeterminateSystems/nix-installer-action@main
    - name: Update lockfile
      run: nix/update-wlroots.sh

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[gha] Nix: update wlroots"
